homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London

frontend:
config:
http:
updater:
conversation:
history:
logbook:

sensor:
  - platform: tube_state
    line:
      - Bakerloo
      - Central
      - Circle
      - District
      - Hammersmith-city
      - Jubilee
      - Metropolitan
      - Northern
      - Piccadilly
      - Victoria
      - Waterloo-city

  - platform: template
    sensors:
      circle_line_description:
        value_template: '{{states.sensor.circle.attributes.Description}}'
        friendly_name: 'Circle line info'

group:
  default_view:
    view: yes
    icon: mdi:home
    entities:
      - group.London_tubes_group

  London_tubes_group:
    name: London tube status
    entities:
      - sensor.bakerloo
      - sensor.central
      - sensor.circle
      - sensor.circle_line_description
  #    - sensor.district
  #    - sensor.hammersmithcity
  #    - sensor.jubilee
  #    - sensor.metropolitan
  #    - sensor.northern
  #    - sensor.piccadilly
  #    - sensor.victoria
  #    - sensor.waterloocity
