homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London

frontend:
config:
http:
updater:
conversation:
history:
logbook:

sensor:
  - platform: tube_state
    line:
      - Bakerloo
      - Central
      - Circle
      - District
      - DLR
      - Hammersmith & City
      - Jubilee
      - London Overground
      - Metropolitan
      - Northern
      - Piccadilly
      - TfL Rail
      - Victoria
      - Waterloo & City

group:
  default_view:
    view: yes
    icon: mdi:home
    entities:
      - group.London_tubes_group

  London_tubes_group:
    name: London tube status
    entities:
      - sensor.bakerloo
      - sensor.central
      - sensor.circle
      - sensor.district
      - sensor.dlr
      - sensor.hammersmith__city
      - sensor.jubilee
      - sensor.london_overground
      - sensor.metropolitan
      - sensor.northern
      - sensor.piccadilly
      - sensor.tfl_rail
      - sensor.victoria
      - sensor.waterloo__city
